name: Build and deploy to ECS
on:
    push:
        branches:
            -main

jobs:
   build-deploy:
      runs-on: ubuntu-latest
      permissions:
          contents: read
          packages: write

      steps:
        ## clone repo. into the runner

         - name: clone repo
           uses: actions/checkout@3
           with:
                  distribution: 'adopt'
                  java-version: '11'
                  ## create  artifact  with maven
         - name: package-artifact
           run: mvn package  ##validate,compile  and  code, unit test, package code into an artifact
         - name: Run SonarQube Analysis
           run: mvn sonar:sonar \
                -Dsonar.projectKey=samir-webapp-project \
                -Dsonar.host.url=http://3.14.145.127:9000 \
                -Dsonar.login=b484ee9100460888e1eb6eb04fd6e392cfd87fc3
   
         - name: publish to  github packages
           run: mvn --batch-mode deploy
           env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

                ## have github actons authenticate to aws thrrough OIDC

         - name: auth to aws
           uses: aws-actions/configure-aws-credentials@v3
           with: 
               role-to-assume: 
               aws-region: us-east-1

               ##use docker to containerise artifact

         - name: build,tag and push
           id: build-image
           env:
              REGISTRY:${{steps.login-ecr.outputs.registry}}
              REPOSITORY:
              IMAGE_TAG: ${{github.sha}} 

